package vn.edu.vnu.uet.fit.entity;
// Generated May 11, 2016 1:11:24 PM by Hibernate Tools 4.3.1

// Generated May 11, 2016 1:11:24 PM by Hibernate Tools 4.3.1



/**
 * Courseusers generated by hbm2java
 */
public class Courseusers  implements java.io.Serializable {


     private Integer courseUserId;
     private Users user;
     private Courses course;
     private Courseusersrole roleInCourse;

    public Courseusers() {
    }

    public Courseusers(Users user, Courses course) {
        this.user = user;
        this.course = course;
    }

    public Courseusers(Users user, Courses course, Courseusersrole roleInCourse) {
        this.user = user;
        this.course = course;
        this.roleInCourse = roleInCourse;
    }

    public Integer getCourseUserId() {
        return this.courseUserId;
    }
    
    public void setCourseUserId(Integer courseUserId) {
        this.courseUserId = courseUserId;
    }

    public Users getUser() {
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    public Courses getCourse() {
        return course;
    }

    public void setCourse(Courses course) {
        this.course = course;
    }

    public Courseusersrole getRoleInCourse() {
        return roleInCourse;
    }

    public void setRoleInCourse(Courseusersrole roleInCourse) {
        this.roleInCourse = roleInCourse;
    }
    
}


