package vn.edu.vnu.uet.fit.entity;
// Generated May 11, 2016 1:11:24 PM by Hibernate Tools 4.3.1



/**
 * Courseproblems generated by hbm2java
 */
public class Courseproblems  implements java.io.Serializable {


     private Integer courseProblemId;
     private Courses course;
     private Problems problem;
     private Integer hardLevel;
     private int scoreInCourse;
     private boolean isActive;

    public Courseproblems() {
    }

	
    public Courseproblems(int scoreInCourse, boolean isActive) {
        this.scoreInCourse = scoreInCourse;
        this.isActive = isActive;
    }
    public Courseproblems(Courses course, Problems problem, Integer hardLevel, int scoreInCourse, boolean isActive) {
       this.course = course;
       this.problem = problem;
       this.hardLevel = hardLevel;
       this.scoreInCourse = scoreInCourse;
       this.isActive = isActive;
    }
   
    public Integer getCourseProblemId() {
        return this.courseProblemId;
    }
    
    public void setCourseProblemId(Integer courseProblemId) {
        this.courseProblemId = courseProblemId;
    }
    public Courses getCourse() {
        return this.course;
    }
    
    public void setCourse(Courses course) {
        this.course = course;
    }
    public Problems getProblem() {
        return this.problem;
    }
    
    public void setProblem(Problems problem) {
        this.problem = problem;
    }
    public Integer getHardLevel() {
        return this.hardLevel;
    }
    
    public void setHardLevel(Integer hardLevel) {
        this.hardLevel = hardLevel;
    }
    public int getScoreInCourse() {
        return this.scoreInCourse;
    }
    
    public void setScoreInCourse(int scoreInCourse) {
        this.scoreInCourse = scoreInCourse;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


