package vn.edu.vnu.uet.fit.entity;
// Generated May 11, 2016 1:11:24 PM by Hibernate Tools 4.3.1



/**
 * Examproblems generated by hbm2java
 */
public class Examproblems  implements java.io.Serializable {


     private Integer examProblemId;
     private int examId;
     private int problemId;
     private Integer scoreInExam;
     private boolean isActive;

    public Examproblems() {
    }

	
    public Examproblems(int examId, int problemId, boolean isActive) {
        this.examId = examId;
        this.problemId = problemId;
        this.isActive = isActive;
    }
    public Examproblems(int examId, int problemId, Integer scoreInExam, boolean isActive) {
       this.examId = examId;
       this.problemId = problemId;
       this.scoreInExam = scoreInExam;
       this.isActive = isActive;
    }
   
    public Integer getExamProblemId() {
        return this.examProblemId;
    }
    
    public void setExamProblemId(Integer examProblemId) {
        this.examProblemId = examProblemId;
    }
    public int getExamId() {
        return this.examId;
    }
    
    public void setExamId(int examId) {
        this.examId = examId;
    }
    public int getProblemId() {
        return this.problemId;
    }
    
    public void setProblemId(int problemId) {
        this.problemId = problemId;
    }
    public Integer getScoreInExam() {
        return this.scoreInExam;
    }
    
    public void setScoreInExam(Integer scoreInExam) {
        this.scoreInExam = scoreInExam;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


