package vn.edu.vnu.uet.fit.entity;
// Generated May 11, 2016 1:11:24 PM by Hibernate Tools 4.3.1



/**
 * Semesters generated by hbm2java
 */
public class Semesters  implements java.io.Serializable {


     private Integer semesterId;
     private String semesterName;

    public Semesters() {
    }

    public Semesters(String semesterName) {
       this.semesterName = semesterName;
    }
   
    public Integer getSemesterId() {
        return this.semesterId;
    }
    
    public void setSemesterId(Integer semesterId) {
        this.semesterId = semesterId;
    }
    public String getSemesterName() {
        return this.semesterName;
    }
    
    public void setSemesterName(String semesterName) {
        this.semesterName = semesterName;
    }

    @Override
    public boolean equals(Object obj) {
        if(obj instanceof Semesters){
            return ((Semesters)obj).getSemesterId() == getSemesterId();
        }else{
            return false;
        }
    }




}


