package vn.edu.vnu.uet.fit.entity;
// Generated May 11, 2016 1:11:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Submissions generated by hbm2java
 */
public class Submissions  implements java.io.Serializable {


     private Integer submitId;
     private Problems problem;
     private Exams exam;
     private Courses course;
     private Users user;
     private Date submitTime;
     private String language;
     private String sourceCode;
     private Float runningTime;
     private String result;
     private Integer resultScore;
     private boolean isActive;

    public Submissions() {
    }

	
    public Submissions(Problems problem, Users user, Date submitTime, boolean isActive) {
        this.problem = problem;
        this.user = user;
        this.submitTime = submitTime;
        this.isActive = isActive;
    }
    public Submissions(Problems problem, Exams exam, Courses course, Users user, Date submitTime, String language, String sourceCode, Float runningTime, String result, Integer resultScore, boolean isActive) {
       this.problem = problem;
       this.exam = exam;
       this.course = course;
       this.user = user;
       this.submitTime = submitTime;
       this.language = language;
       this.sourceCode = sourceCode;
       this.runningTime = runningTime;
       this.result = result;
       this.resultScore = resultScore;
       this.isActive = isActive;
    }
   
    public Integer getSubmitId() {
        return this.submitId;
    }
    
    public void setSubmitId(Integer submitId) {
        this.submitId = submitId;
    }

    public Problems getProblem() {
        return problem;
    }

    public void setProblem(Problems problem) {
        this.problem = problem;
    }

    public Exams getExam() {
        return exam;
    }

    public void setExam(Exams exam) {
        this.exam = exam;
    }

    public Courses getCourse() {
        return course;
    }

    public void setCourse(Courses course) {
        this.course = course;
    }

    public Users getUser() {
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
    }
    
    public Date getSubmitTime() {
        return this.submitTime;
    }
    
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getSourceCode() {
        return this.sourceCode;
    }
    
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }
    public Float getRunningTime() {
        return this.runningTime;
    }
    
    public void setRunningTime(Float runningTime) {
        this.runningTime = runningTime;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public Integer getResultScore() {
        return this.resultScore;
    }
    
    public void setResultScore(Integer resultScore) {
        this.resultScore = resultScore;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


