package vn.edu.vnu.uet.fit.entity;
// Generated May 11, 2016 1:11:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Submissions generated by hbm2java
 */
public class Submissions  implements java.io.Serializable {


     private Integer submitId;
     private int problemId;
     private Integer examId;
     private Integer courseId;
     private int userId;
     private Date submitTime;
     private String language;
     private String sourceCode;
     private Float runningTime;
     private String result;
     private Integer resultScore;
     private boolean isActive;

    public Submissions() {
    }

	
    public Submissions(int problemId, int userId, Date submitTime, boolean isActive) {
        this.problemId = problemId;
        this.userId = userId;
        this.submitTime = submitTime;
        this.isActive = isActive;
    }
    public Submissions(int problemId, Integer examId, Integer courseId, int userId, Date submitTime, String language, String sourceCode, Float runningTime, String result, Integer resultScore, boolean isActive) {
       this.problemId = problemId;
       this.examId = examId;
       this.courseId = courseId;
       this.userId = userId;
       this.submitTime = submitTime;
       this.language = language;
       this.sourceCode = sourceCode;
       this.runningTime = runningTime;
       this.result = result;
       this.resultScore = resultScore;
       this.isActive = isActive;
    }
   
    public Integer getSubmitId() {
        return this.submitId;
    }
    
    public void setSubmitId(Integer submitId) {
        this.submitId = submitId;
    }
    public int getProblemId() {
        return this.problemId;
    }
    
    public void setProblemId(int problemId) {
        this.problemId = problemId;
    }
    public Integer getExamId() {
        return this.examId;
    }
    
    public void setExamId(Integer examId) {
        this.examId = examId;
    }
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Date getSubmitTime() {
        return this.submitTime;
    }
    
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getSourceCode() {
        return this.sourceCode;
    }
    
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }
    public Float getRunningTime() {
        return this.runningTime;
    }
    
    public void setRunningTime(Float runningTime) {
        this.runningTime = runningTime;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public Integer getResultScore() {
        return this.resultScore;
    }
    
    public void setResultScore(Integer resultScore) {
        this.resultScore = resultScore;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


