package vn.edu.vnu.uet.fit.entity;
// Generated May 11, 2016 1:11:24 PM by Hibernate Tools 4.3.1



/**
 * Userrole generated by hbm2java
 */
public class Userrole  implements java.io.Serializable {


     private Integer roleId;
     private String roleName;

    public Userrole() {
    }

    public Userrole(String roleName) {
       this.roleName = roleName;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Override
    public boolean equals(Object obj) {
        if(obj instanceof Userrole){
            return ((Userrole)obj).getRoleId() == getRoleId();
        }else{
            return false;
        }
    }




}


